# Generated by Django 4.0.4 on 2022-06-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('rating', models.CharField(blank=True, max_length=1)),
                ('job', models.TextField(max_length=255)),
            ],
        ),
    ]
