# Generated by Django 4.0.4 on 2022-06-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('rating', models.CharField(blank=True, max_length=1)),
                ('job', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='MentorList',
        ),
    ]
